# this is the name of the workflow - I have given it an imaginary name "test" - 
# - feel free to give it a name of your choice
name: test

# on is the type of action that will trigger the workflow. For instance when someone pushes code 
# or raises a PR. You can also optionally specificy the name of the branch - but this is optional
on:
  push:
    branches: [ master ]
  pull_request:
    types: [ master ]
#jobs refer to the actual tasks that will run when the workflow is triggered - example approve and automerge
jobs:

# Here I have a job name "test" .As I said please feel free to give it a name of your choice 
  test:
# run-on is the type of architecture the workflow will run on
# for MAC and linux uses - preferbly use Ubuntu-latest. For window uses - use windows latest
    runs-on: ubuntu-latest
# steps refers to a sequence of tasks after the workflow file is triggered.
    steps:
# "uses" is the type of action - remember their are so many actions in the github marketplace
      - uses: actions/checkout@v2
# this is the name of the currently running task
      - name: run hello world
# finally, the "run" keyword writes something to the screen.
        run: echo Hello world

